#!/usr/bin/env bash

stty cols 80
stty rows 20

language=$1
tests=$(find "./tests/${language}" ! -name '*.go' -printf '%P\n')

for t in ${tests}; do
  if [[ $t != *.exp ]]; then
    echo "$t:"
    continue
  fi

  name=$(echo -n $t | sed -s 's/.*\/\(.*\).exp/\1/' | sed -s 's/_/ /g')

  echo -n "...    ${language} $name"
  

  test_out=$(timeout 15 expect -f "./tests/${language}/$t" 2>&1)
  if [[ $? != 0 ]]; then
    echo -e "\n========== \"$t\" failed =========="
    echo "$test_out"
    exit 1
  fi

  echo -ne '\r'
  echo -e "      \e[32m✓\e[0m $name"
done

if [[ $language == 'nodejs' && $DISABLE_GO_TESTS != 1 ]]; then
  echo running go tests
  go test ./tests/nodejs
fi
