#!/usr/bin/env bash

set -e
set -o pipefail

COMPILE_DIR="$(dirname "$0")"
DEST_DIR="$COMPILE_DIR/../../prybar_assets/sqlite"
mkdir -p "$DEST_DIR"
gcc -Wall -shared -fPIC -ldl -o "$DEST_DIR/patch.so" "$COMPILE_DIR/patch/patch.c"
