#!/usr/bin/expect -f

set timeout -1
spawn ./prybar-tcl -q -i ./test_files/hello_tcl.tcl
match_max 100000
expect -exact "Hello, Tcl!\r\r
--> "
send -- "p"
expect -exact "\r--> p\[0K\r\[5C"
send -- "u"
expect -exact "\r--> pu\[0K\r\[6C"
send -- "t"
expect -exact "\r--> put\[0K\r\[7C"
send -- "s"
expect -exact "\r--> puts\[0K\r\[8C"
send -- " "
expect -exact "\r--> puts \[0K\r\[9C"
send -- "\$"
expect -exact "\r--> puts \$\[0K\r\[10C"
send -- "m"
expect -exact "\r--> puts \$m\[0K\r\[11C"
send -- "y"
expect -exact "\r--> puts \$my\[0K\r\[12C"
send -- "_"
expect -exact "\r--> puts \$my_\[0K\r\[13C"
send -- "n"
expect -exact "\r--> puts \$my_n\[0K\r\[14C"
send -- "u"
expect -exact "\r--> puts \$my_nu\[0K\r\[15C"
send -- "m"
expect -exact "\r--> puts \$my_num\[0K\r\[16C"
send -- "\r"
expect -exact "\r--> puts \$my_num\[0K\r\[16C\r
1000\r\r
\r
--> "
send -- ""
expect eof
