#!/usr/bin/expect -f

set timeout -1
spawn ./prybar-tcl -q -i
match_max 100000
expect -exact "--> "
send -- "h"
expect -exact "\r--> h\[0K\r\[5C"
send -- "m"
expect -exact "\r--> hm\[0K\r\[6C"
send -- "m"
expect -exact "\r--> hmm\[0K\r\[7C"
send -- "m"
expect -exact "\r--> hmmm\[0K\r\[8C"
send -- "m"
expect -exact "\r--> hmmmm\[0K\r\[9C"
send -- "m"
expect -exact "\r--> hmmmmm\[0K\r\[10C"
send -- "\r"
expect -exact "\r--> hmmmmm\[0K\r\[10C\r
error: invalid command name \"hmmmmm\"\r
\r
--> "
send -- ""
expect eof
