#!/usr/bin/expect -f

set timeout -1
spawn ./prybar-scala -i test_files/sumofsquares.scala
match_max 100000
expect -exact "Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 11.0.5).\r
Type in expressions for evaluation. Or try :help.\r
\[35m\r
--> \[0m"
send -- "print(sumOfSquares(,"
expect -exact "\[K"
send -- "3, 4))\r"
expect -exact "3, 4))\r
25\[35m\r
--> \[0m"
send -- ":quit\r"
expect eof
