#!/usr/bin/expect -f

set timeout -1
spawn ./prybar-clojure -c "(defn f \[x\] (inc x))" -e "(def s \"bar\")" -I -i ./test_files/hello.clj
match_max 100000
expect -exact "hello\r"
expect -exact "#'user/f\r"
expect -exact "#'user/s\r"
expect -exact "user=> "

# defined in ./test_files/hello.clj
send -- "a\r"
expect -exact "a\r"
expect -exact "\"hello\"\r"
expect -exact "user=> "

# defined in ./test_files/hello.clj
send -- "b\r"
expect -exact "b\r"
expect -exact "42\r"
expect -exact "user=> "

# defined with "-c"
send -- "(f b)\r"
expect -exact "(f b)\r"
expect -exact "43\r"
expect -exact "user=> "

# defined with  "-e"
send -- "s\r"
expect -exact "s\r"
expect -exact "\"bar\"\r"
expect -exact "user=> "

send -- ""
expect eof

