#!/usr/bin/expect -f

# ignore ANSI escape sequences
set _ "(?:.*?)"

set timeout -1
spawn ./prybar-clojure -c {(defn f [x] (inc x))} -e {(def s "bar")} -I -i -q ./test_files/hello.clj
match_max 100000
expect -re "^${_}#'user/s${_}\r
${_}hello${_}\r
${_}user--> $"

# a is defined in ./test_files/hello.clj
send -- "hello/a\r"
expect -re "^${_}hello/a${_}\r
${_}\"hello\"${_}\r
${_}user--> $"

# b is defined in ./test_files/hello.clj
send -- "hello/b\r"
expect -re "^${_}hello/b${_}\r
${_}42${_}\r
${_}user--> $"

# defined with "-c"
send -- "(f hello/b)\r"
expect -re "^${_}(f hello/b)${_}\r
${_}43${_}\r
${_}user--> $"

# defined with  "-e"
send -- "s\r"
expect -re "^${_}s${_}\r
${_}\"bar\"${_}\r
${_}user--> $"

send -- ""
expect eof

