#!/usr/bin/expect -f

# ignore ANSI escape sequences
set _ "(?:.*?)"

set timeout -1
spawn ./prybar-clojure -i
match_max 100000
expect -re "^${_}Clojure${_}\r
${_}--> $"

send -- "(print \"hello!\")\r"
expect -re "^${_}\\(print \"hello!\"\\)${_}\r
${_}hello!nil${_}\r
${_}--> $"

send -- "(print (+ 1 1))\r"
expect -re "^${_}\\(print \\(\\+ 1 1\\)\\)${_}\r
${_}2nil${_}\r
${_}--> $"

send -- ""
expect eof

