#!/usr/bin/expect -f

set timeout -1
spawn ./prybar-clojure -i
match_max 100000
expect -re {Clojure (?:.*)} # ignore version
expect -exact "user=> "

send -- "(print \"hello!\")\r"
expect -exact "(print \"hello!\")\r"
expect -exact "hello!nil\r"
expect -exact "user=> "

send -- "(print (+ 1 1))\r"
expect -exact "(print (+ 1 1))\r"
expect -exact "2nil\r"
expect -exact "user=> "

send -- ""
expect eof
