#!/bin/bash

cat << EOF > $1
// generated by $0 $*; DO NOT EDIT

package main

import "encoding/base64"

func File(name string) ([]byte, error) {

	switch name {

EOF

for fn in $(ls | egrep -i '.*\.(clj|js|ml)'); do

	echo "		case \"$fn\":" >> $1
	echo "			return base64.StdEncoding.DecodeString(\"$(base64 -i $fn | tr -d \\n)\")" >> $1

done

cat << EOF >> $1

	}
	return nil, nil
}
EOF

echo "Generated $(realpath $1)"
