#!/usr/bin/expect -f

set timeout -1
spawn ./prybar-nodejs -i -q
match_max 100000
expect -exact "\[1G\[0J--> \[5G"
send -- "x\r"
expect -exact "x\r\r
\[0m\[31mReferenceError: x is not defined\r
    at REPL1:1:1\r
    at Script.runInThisContext (vm.js:133:18)\r
    at REPLServer.defaultEval (repl.js:486:29)\r
    at bound (domain.js:416:15)\r
    at REPLServer.runBound \[as eval\] (domain.js:427:12)\r
    at REPLServer.onLine (repl.js:819:10)\r
    at REPLServer.emit (events.js:376:20)\r
    at REPLServer.emit (domain.js:470:12)\r
    at REPLServer.Interface._onLine (readline.js:342:10)\r
    at REPLServer.Interface._line (readline.js:671:8)\[0m\[1G\[0J--> \[5G"
send -- ""
expect eof
